services:
  - type: web
    name: football-auction
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --threads 2 --worker-class gthread --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
    plan: free

